//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovelWeb_SS5.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Chuong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chuong()
        {
            this.Comments = new HashSet<Comment>();
        }

        public int idChuong { get; set; }
        [DisplayName("Số Chương")]
        public string soChuong { get; set; }
        [DisplayName("Tên Chương")]
        public string tenChuong { get; set; }
        [DisplayName("Nội Dung")]
        public string noiDung { get; set; }

        public Nullable<int> idTruyen { get; set; }

        public virtual Truyen Truyen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
