//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovelWeb_SS5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int idCmt { get; set; }
        public string noiDungcmt { get; set; }
        public Nullable<System.DateTime> ngay { get; set; }
        public string userName { get; set; }
        public Nullable<int> idChuong { get; set; }
        public Nullable<int> idUser { get; set; }
    
        public virtual Chuong Chuong { get; set; }
        public virtual User User { get; set; }
    }
}
