//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovelWeb_SS5.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class TheLoai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TheLoai()
        {
            this.Truyens = new HashSet<Truyen>();
        }

        public int idTL { get; set; }
        [DisplayName("Thể Loại")]
        public string tenLoai { get; set; }
        public bool ischecked
        {
            get;
            set;
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Truyen> Truyens { get; set; }
    }
    public class TheLoaiModel
    {
        public List<TheLoai> TheLoaisModel { get; set; }
    }
}
