//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovelWeb_SS5.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Comments = new HashSet<Comment>();
        }

        public int idUser { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Hãy nhập username")]
        [DataType(DataType.Text)]
        [DisplayName("User Name")]
        public string userName { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Password không được để trống")]
        [DataType(DataType.Password)]
        [DisplayName("Password")]
        [StringLength(maximumLength: 25, MinimumLength = 3, ErrorMessage = "Độ dài từ 3 đến 25 ký tự")]
        public string passWord { get; set; }

        public string ErrorMessageLogged { get; set; }
        [DisplayName("Họ Tên")]
        public string hoTen { get; set; }
        public Nullable<int> idQuyen { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [DisplayName("Quyền")]
        public virtual PhanQuyen PhanQuyen { get; set; }
    }
}
